const pages = [
  {
    title: "Home",
    href: "../HomeScreen/index.html",
    iconClasses: "fas fa-home"
  },
  {
    title: "Explore",
    href: "../ExploreScreen/index.html",
    iconClasses: "fa fa-hashtag"
  },
  {
    title: "Notifications",
    href: "../notifications.html",
    iconClasses: "fa fa-bell"
  },
  {
    title: "Messages",
    href: "../messages.html",
    iconClasses: "fas fa-envelope"
  },
  {
    title: "Bookmarks",
    href: "../bookmarks.html",
    iconClasses: "fas fa-bookmark"
  },
  {
    title: "Lists",
    href: "../lists.html",
    iconClasses: "fas fa-list"
  },
  {
    title: "Profile",
    href: "../profile.html",
    iconClasses: "fas fa-user"
  },
  {
    title: "More",
    href: "#",
    iconClasses: "fas fa-ellipsis-h"
  }
]

export default pages
